# Uptime-Kuma
# A "self-hosted monitoring tool like 'Uptime Robot'."
#
# Modifed from louislam
# GitHub: https://github.com/jkocianICA/ica-it-compose/blob/main/Uptime-Kuma_docker-compose.yml

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
      
networks:
  default:
    name: it-primary
    external: true 
